version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Forward the port used by your Node.js application
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres # Set the environment variable for connecting to the PostgreSQL database
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db # Ensures the db service is started before the app service
    command: npm run dev

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./init-db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

volumes:
  postgres-data:
